TANK_SPEED = 1
AIRPLANE_SPEED = 8
ARTILLERY_SPEED = 1
HELICOPTER_SPEED = 2
ANTITANK_SPEED = 1
IRONDOME_SPEED = 1
SPY_SPEED = 1
SATELITE_SPEED = 32
BUILDER_SPEED = 1

AIRPLANE_MAX_TIME_IN_AIR = 16
HELICOPTER_MAX_TIME_IN_AIR = 8

HELICOPTER_ATTACK_RANGE = 1
ARTILLERY_ATTACK_RANGE = 3

BUNKER_DEFEND_MULTIPLIER = 5
ARTILLERY_DEFEND_RANGE = 2
IRONDOME_DEFEND_RANGE = 10
MAX_DEFENDER_RANGE = max(ARTILLERY_DEFEND_RANGE, IRONDOME_DEFEND_RANGE)

TANK_PRICE = 8
AIRPLANE_PRICE = 20
ARTILLERY_PRICE = 8
HELICOPTER_PRICE = 16
ANTITANK_PRICE = 10
IRONDOME_PRICE = 32
BUNKER_PRICE = 10
SPY_PRICE = 20
TOWER_PRICE = 16
SATELITE_PRICE = 64
BUILDER_PRICE = 20

TOWER_SIGHTING_RANGE = 5
SATELITE_SIGHTING_RANGE = 10

BUILDER_MAX_COLLECTION_IN_TURN = 5
BUILDER_MAX_MONEY = 100
